<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>TicTacToeMisere.WinFormsUI</RootNamespace>
    <AssemblyName>TicTacToeMisere</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicTacToeMisere.GameLogic\TicTacToeMisere.GameLogic.csproj" />
  </ItemGroup>

</Project>
